//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bunny
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Color { get; set; }
        public short Age { get; set; }
        public decimal Price { get; set; }
    
        public virtual Spaceship Spaceship { get; set; }
    }
}
