//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spaceship
    {
        public Spaceship()
        {
            this.Bunny = new HashSet<Bunny>();
        }
    
        public int Id { get; set; }
        public string Model { get; set; }
    
        public virtual ICollection<Bunny> Bunny { get; set; }
    }
}
