//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int Id { get; set; }
        public int ManufacturerId { get; set; }
        public string Model { get; set; }
        public int TransmisionId { get; set; }
        public System.DateTime Year { get; set; }
        public decimal Price { get; set; }
        public int DealerId { get; set; }
    
        public virtual Dealer Dealer { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual TransmisionType TransmisionType { get; set; }
    }
}
